### ISSUE TITLE
Minor refactoring of synthetic module

### ISSUE THREAD

**Issue by gabiborges1** [latentnetworks/vimure#15]
- [ ] ~~Remove init defaults on `StandardSBM` parameters~~
- [ ] ~~Raise warnings when user does not provide a value to any important parameter~~ (python does that)
- [x] Add docstrings to classes and functions
- [ ] #88
- [x] Rename `binarize_X` to `cutoff_X` 
- [x] Raise a warning if user sets `cutoff_X=True` but does not provide `Q` (not a feature in Python)

**Comment by jonjoncardoso** [comment]
- [ ] Rename functions and internal variables

The linter complains that we're mixing up camelCase and snake_symbols when naming variables and functions

![image](https://github.com/latentnetworks/vimure/assets/896254/5861d0b0-0d82-4157-94d4-29b790a9aa2c)

**Comment by jonjoncardoso** [comment]
Closed with https://github.com/latentnetworks/vimure/commit/faf7c7ad5023287a6d4b2e8e2ee397caf55f51eb
