### ISSUE TITLE
[BUG] Currently allowed to pass malformatted reporters mask to R vimure call

### ISSUE THREAD

**Issue by marioangst** [latentnetworks/vimure#79]
**Describe the bug**
Currently, vimure::vimure calls in R allow passing of malformatted arrays for the R parameter, which seems to ignore the R parameter silently.

**To Reproduce**

```
N <- union(edgelist$ego, edgelist$alter)
l_n <- length(N)

# specify some sort of mask
reporters <- unique(edgelist$ego)

reporter_mask <- array(0,
                       dim = c(1,l_n,l_n,l_n),
                       dimnames = list("layer",N,N,N))

reporter_mask[,,,reporters] <- "clearly_wrong"

vimure(edgelist, R = reporter_mask)
```

**Expected behavior**
An informative error message about the expected format for the parameter R.

**Environment (please complete the following information):**
 - OS: Windows 11
 - R/Python versions: 4.1/ 3.6

**Comment by jonjoncardoso** [comment]
Thanks @marioangst , this is a great report! I will look into this later.

**Comment by marioangst** [comment]
@jonjoncardoso thanks for the package. It is something that should be incredibly useful for people, once the initial bugs have been ironed out and documentation is improved I think.
